name: csnet
channels:
  - conda-forge
  - bioconda
dependencies:
  - altair
  - codecov
  - conda-build
  - coverage
  - dca
  - dask
  - fire
  - ipython
  - jupyterlab
  - networkx
  - numba
  - numpy
  - pandas
  - pre_commit
  - pytest
  - pytest-cov
  - python=3.6
  - python-chromedriver-binary
  - scanpy
  - scikit-learn
  - scipy
  - selenium
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - vega_datasets
