name: gsel
channels:
  - conda-forge
  - bioconda
dependencies:
  - altair
  - codecov
  - conda-build
  - coverage
  - dca
  - ipython
  - jupyterlab
  - matplotlib
  - natsort
  - numba
  - numpy
  - pandas
  - pre_commit
  - pytest
  - pytest-cov
  - python=3.6
  - scanpy
  - scikit-learn
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - vega_datasets
